# ------------------------------------------------------------------------------------------------
# ❤️ Use Compose Spec: https://www.compose-spec.io/ ❤️
#
# This file builds a containerized instance of Weeding Helper behind Traefik as a reverse proxy.
# Images for Traefik and Ofelia are pulled from their respective authorities on Docker Hub.
# Application image is pulled from OhioNet via Docker Hub.
# -------------------------------------------------------------------------------------------------

# --------------------------
# Docker Networking Setup
# --------------------------
networks:
  weeding-helper:
    internal: true
  gateway:
    external: true

# --------------------------
# Docker Volume for MariaDB
# --------------------------
volumes:
  weeding-helper-data:


services:
# ------------------------------------------------
# Weeding Helper Application Code
# ------------------------------------------------
  weeding-helper-app:
    container_name: weeding-helper-app
    image: ohionet/weeding-helper-app:latest
    labels:
    #--------------------------------------------------------------------#
    # Define the behavior and rules of Weeding Helper w/ Traefik         #
    #--------------------------------------------------------------------#
      - "traefik.enable=true" # Enable traefik on this container
      - "traefik.http.routers.weeding.entrypoints=http" # Enable HTTP entrypoint for [portainer]
      - "traefik.http.routers.weeding.rule=Host(`weeding.opal-libraries.org`)" # Define HTTP host
      - "traefik.http.routers.weeding.middlewares=redirect@file" # Enforce HTTPS redirect
      - "traefik.http.routers.weeding-ssl.entrypoints=https" # Enable HTTPS entrypoint for [portainer-ssl]
      - "traefik.http.routers.weeding-ssl.rule=Host(`weeding.opal-libraries.org`)" # Define HTTPS host
      - "traefik.http.routers.weeding-ssl.tls.certresolver=letsencrypt" # Use Let's Encrypt
    restart: unless-stopped
    networks:
      - weeding-helper
      - gateway


# ------------------------------------------------
# MariaDB Database Instance for Weeding Helper
#
# NOTE: The MYSQL_* environment variables below
# need to match the values used in config.php
# ------------------------------------------------
  weeding-helper-db:
    container_name: weeding-helper-db
    image: ohionet/weeding-helper-db:latest
    restart: unless-stopped
    volumes:
      - weeding-helper-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - weeding-helper


# ------------------------------------------------------
# Ofelia: docker job scheduler (aka. crontab for docker)
# ------------------------------------------------------
  ofelia:
    container_name: ofelia
    image: mcuadros/ofelia:latest
    restart: always
    depends_on:
      - weeding-helper-app
    volumes:
      - "./ofelia.ini:/etc/ofelia/config.ini"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - weeding-helper